/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nurteen_prometheus_pc_framework_utils_TimeUtils */

#ifndef _Included_nurteen_prometheus_pc_framework_utils_TimeUtils
#define _Included_nurteen_prometheus_pc_framework_utils_TimeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nurteen_prometheus_pc_framework_utils_TimeUtils
 * Method:    currentTimeNsecs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nurteen_prometheus_pc_framework_utils_TimeUtils_currentTimeNsecs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
